on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, auto_merge_disabled, auto_merge_enabled, ready_for_review ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create local changes and commit
        run: |
          echo test 
