on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NNNNNNNNOOOOOOO
        run: |
          echo test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nonononononononononecho test 
          echo nononononononononon
